"""facility table

Revision ID: 6313af5a6bab
Revises: 
Create Date: 2020-11-30 04:48:03.792541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6313af5a6bab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('time', sa.String(length=600), nullable=True),
    sa.Column('home_url', sa.String(length=600), nullable=True),
    sa.Column('menu_url', sa.String(length=600), nullable=True),
    sa.Column('reserv_url', sa.String(length=600), nullable=True),
    sa.Column('phone_num', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_category'), 'facility', ['category'], unique=True)
    op.create_index(op.f('ix_facility_home_url'), 'facility', ['home_url'], unique=True)
    op.create_index(op.f('ix_facility_menu_url'), 'facility', ['menu_url'], unique=True)
    op.create_index(op.f('ix_facility_name'), 'facility', ['name'], unique=True)
    op.create_index(op.f('ix_facility_phone_num'), 'facility', ['phone_num'], unique=True)
    op.create_index(op.f('ix_facility_reserv_url'), 'facility', ['reserv_url'], unique=True)
    op.create_index(op.f('ix_facility_time'), 'facility', ['time'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_time'), table_name='facility')
    op.drop_index(op.f('ix_facility_reserv_url'), table_name='facility')
    op.drop_index(op.f('ix_facility_phone_num'), table_name='facility')
    op.drop_index(op.f('ix_facility_name'), table_name='facility')
    op.drop_index(op.f('ix_facility_menu_url'), table_name='facility')
    op.drop_index(op.f('ix_facility_home_url'), table_name='facility')
    op.drop_index(op.f('ix_facility_category'), table_name='facility')
    op.drop_table('facility')
    # ### end Alembic commands ###
